language: python
python:
  - "2.7"
install: python setup_development.py
script: python test.py
notifications:
  irc:
    channels:
      - "irc.mozilla.org#ateam"
    on_success: change
    on_failure: always
  email:
    recipients:
      - auto-tools@mozilla.com
    on_success: change
    on_failure: always
